# Cấu hình dữ liệu
data:
  known_faces: "../data/known_faces/"
  known_faces_processed: "../data/known_faces_processed/"

# Cấu hình đường dẫn
paths:
  encodings_file: "../models/face_encodings.pkl"
  svm_model_file: "../models/face_recognition_svm.pkl"
  error_log_file: "../logs/error.log"
  info_log_file: "../logs/info.log"
  output_video_path: "../output/recognition_output.mp4"

# Cấu hình InsightFace
insightface:
  model_name: "buffalo_l"
  det_size: [640, 640]
  distance_threshold: 0.6

# Cấu hình nhận diện
recognition:
  process_frame_interval: 20

# Cấu hình logging
logging:
  enable: true
  level: "INFO"

# Cấu hình GUI
gui:
  window_size: [800, 600]
  gradient_colors:
    start: [50, 150, 255]
    end: [255, 255, 255]
  button_style:
    background: [76, 175, 80]
    hover: [69, 160, 73]
    text_color: [255, 255, 255]
  font:
    title: "Arial, 24, bold"
    button: "Arial, 14, bold"